using Microsoft.CodeAnalysis;

namespace Mapstor.Generator.Templates;

internal class MappingTemplate
{
    public const string SourceVarName = "source";
    public const string TargetGenericTypeName = "TargetType";
    public const string MapMethodName = "MapTo";

    public static string PropertyAssignment(string sourcePropName, string targetPropName) => $"{targetPropName} = {SourceVarName}.{sourcePropName}";

    public static string TargetMethodBlock(INamedTypeSymbol sourceType, INamedTypeSymbol targetType, string assignments)
    {
        var template = $@"
        public static {targetType.ToDisplayString()} {MapMethodName}{targetType.Name}({sourceType.ToDisplayString()} {SourceVarName})
        {{
            return new {targetType.ToDisplayString()}
            {{
                {assignments}
            }}; 
        }}";

        return template;
    }

    public static string MappingDictionaryEntry(INamedTypeSymbol targetType)
    {
        var template = $@"
            {{ typeof({targetType.ToDisplayString()}), {SourceVarName} => {MapMethodName}{targetType.Name}({SourceVarName}) }},";
        return template;
    }

    public static string MappingBlock(INamedTypeSymbol sourceType, string mappingDictionaryEntries, string mappingTargetMethods)
    {
        var template = $@"
        private static readonly Dictionary<Type, Func<{sourceType.ToDisplayString()}, object>> _mappers = new()
        {{
            {mappingDictionaryEntries}
        }};
        
        {mappingTargetMethods}";
        return template;
    }

    public static string ExtensionMethodMapTo(INamedTypeSymbol sourceType, string targetMethodBlocks)
    {
        var sourceNamespace = sourceType.ContainingNamespace;

        var template = 
$@"
// <auto-generated />
using System;
using System.Collections.Generic;

namespace {sourceNamespace}
{{
    public static partial class {sourceType.Name}MappingExtensions
    {{
        {targetMethodBlocks}

        public static {TargetGenericTypeName} MapTo<{TargetGenericTypeName}>(this {sourceType.ToDisplayString()} {SourceVarName}) where {TargetGenericTypeName} : class
        {{
            if ({SourceVarName} is null) throw new ArgumentNullException(nameof({SourceVarName}));

            if (_mappers.TryGetValue(typeof({TargetGenericTypeName}), out var mapper))
            {{
                return (mapper({SourceVarName}) as {TargetGenericTypeName})!;
            }}

            throw new NotSupportedException($""No mapping from {sourceType.Name} to {{typeof({TargetGenericTypeName}).Name}}"");
        }}
    }}
}}";
        return template;
    }

}
